In [24]:
#Importing data
import pandas as pd
import numpy as np
import re

df = pd.read_csv('original_dataset.csv', low_memory = False, dtype = {'locality': str, 'postcode': str, 'property_subtype': str})
test_df = df

#Adding two column for data processing
if 'loc_clean' not in test_df.columns:
    index = test_df.columns.get_loc('locality')+1
    test_df.insert(index, "loc_clean", "clean value")
if 'loc_intermediate' not in test_df.columns: 
    index = test_df.columns.get_loc('loc_clean')+1
    test_df.insert(index, "loc_intermediate", "intermediate value")
if 'loc_dirty' not in test_df.columns:
    index = test_df.columns.get_loc('loc_intermediate')+1
    test_df.insert(index, "loc_dirty", "dirty_value")
    
test_df.head()

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,4180,clean value,intermediate value,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,8730,clean value,intermediate value,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,4020,clean value,intermediate value,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,1200,clean value,intermediate value,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,1190,clean value,intermediate value,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW

In [25]:
#Catch post codes and set them in the intermediate column, set the rest in the dirty box
pattern = re.compile("^\d{4}$")
row_number = -1
for row in test_df["locality"]: 
    row_number+=1
    if type(row) is str: 
        search_result = pattern.search(row)
        if search_result is None: 
            test_df.at[row_number, 'loc_dirty'] = row
        else: 
            test_df.at[row_number, 'loc_intermediate'] = row
            test_df.loc[row_number, 'loc_clean'] = np.nan
            
test_df.head()

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,4180,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,8730,NaN,8730,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,4020,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,1200,NaN,1200,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,1190,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW

In [26]:
row_number = -1
for row in test_df["locality"]:
    row_number+=1
    if row == test_df["postcode"][row_number]: 
        test_df.loc[row_number, 'locality'] = np.nan
        
test_df.head()

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,NaN,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,NaN,NaN,8730,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,NaN,NaN,1200,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,NaN,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW

In [27]:
regex = "\d{4}"
test_df["locality"][test_df["locality"].str.contains(regex, na=False)]

18034        Rue RimiÃ¨re 105, 4120 Rotheux-RimiÃ¨re, NeuprÃ©
18035    Sint-Truidensesteenweg 95A A, 3350 Orsmaal-Gus...
18036               Augustijnenlaan 77 201, 2200 Herentals
18037                  Averbodesesteenweg 19, 2230 Herselt
18038                 Edward pynaertkaai 21, 9050 Ledeberg
                               ...
25653                                          gent-(9000)
31119                                       antwerpen-2000
31120                                       antwerpen-2000
32194                                       antwerpen-2018
68783                                   Middelkerke (8434)
Name: locality, Length: 1653, dtype: object

In [28]:
import re
filter_pattern = re.compile("\d{4}")
pattern = re.compile("([a-zA-ZÃ€-Ã¿-,]+ ){0,}([a-zA-ZÃ€-Ã¿]+)$")
row_number = -1
for row in test_df["locality"]: 
    row_number+=1
    if type(row) is str: 
        filter_criteria = filter_pattern.search(row)
        if filter_criteria is not None: 
            search_result = pattern.search(row)
            if search_result is not None: 
                search_match = pattern.search(row).group()
                test_df.loc[row_number, 'loc_intermediate'] = search_match

#I think I should work with subsets of the data instaed of a filter pattern
#However this would mess up with my row_number

test_df.head()

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,NaN,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,NaN,NaN,8730,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,NaN,NaN,1200,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,NaN,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW

In [29]:
test_df[(~test_df["locality"].isnull()) & (test_df["loc_intermediate"]!= "intermediate value") & test_df["postcode"].isnull()].head(-1000)
#todo : attribute the intermediate to loc_clean 
#todo next : catch value before first comma and set it to address
#todo end : for concerned values, set locality to NaN

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
18034,2,https://www.realo.be/en/rue-rimiere-105-4120-r...,"Rue RimiÃ¨re 105, 4120 Rotheux-RimiÃ¨re, NeuprÃ©",clean value,"Rotheux-RimiÃ¨re, NeuprÃ©","Rue RimiÃ¨re 105, 4120 Rotheux-RimiÃ¨re, NeuprÃ©",NaN,True,House,0,...,False,False,NaN,False,NaN,NaN,No,NaN,False,NaN
18035,2,https://www.realo.be/en/sint-truidensesteenweg...,"Sint-Truidensesteenweg 95A A, 3350 Orsmaal-Gus...",clean value,"Orsmaal-Gussenhoven, Linter","Sint-Truidensesteenweg 95A A, 3350 Orsmaal-Gus...",NaN,True,House,340000â‚¬ 340.000,...,False,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18036,2,https://www.realo.be/en/augustijnenlaan-77-220...,"Augustijnenlaan 77 201, 2200 Herentals",clean value,Herentals,"Augustijnenlaan 77 201, 2200 Herentals",NaN,False,Flat,259000â‚¬ 259.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18037,2,https://www.realo.be/en/averbodesesteenweg-19-...,"Averbodesesteenweg 19, 2230 Herselt",clean value,Herselt,"Averbodesesteenweg 19, 2230 Herselt",NaN,True,House,449000â‚¬ 449.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18038,2,https://www.realo.be/en/edward-pynaertkaai-21-...,"Edward pynaertkaai 21, 9050 Ledeberg",clean value,Ledeberg,"Edward pynaertkaai 21, 9050 Ledeberg",NaN,False,Flat,249900â‚¬ 249.900,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18040,2,https://www.realo.be/en/groenplein-33-9060-zel...,"Groenplein 33 302, 9060 Zelzate",clean value,Zelzate,"Groenplein 33 302, 9060 Zelzate",NaN,False,Flat,159000â‚¬ 159.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18041,2,https://www.realo.be/en/hoogveldstraat-21-3720...,"Hoogveldstraat 21 D, 3720 Kortessem",clean value,Kortessem,"Hoogveldstraat 21 D, 3720 Kortessem",NaN,False,Flat,219000â‚¬ 219.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18042,2,https://www.realo.be/en/eerste-meistraat-4-370...,"Eerste-Meistraat 4, 3700 Tongeren",clean value,Tongeren,"Eerste-Meistraat 4, 3700 Tongeren",NaN,False,Business,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18043,2,https://www.realo.be/en/roeselaarsestraat-84-8...,"Roeselaarsestraat 84 8, 8870 Izegem",clean value,Izegem,"Roeselaarsestraat 84 8, 8870 Izegem",NaN,False,Flat,247000â‚¬ 247.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18044,2,https://www.realo.be/en/meikeverstraat-12-2250...,"Meikeverstraat 12, 2250 Olen",clean value,Olen,"Meikeverstraat 12, 2250 Olen",NaN,True,House,379000â‚¬ 379.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18045,2,https://www.realo.be/en/salvialaan-31-2260-oev...,"Salvialaan 31, 2260 Oevel, Westerlo",clean value,"Oevel, Westerlo","Salvialaan 31, 2260 Oevel, Westerlo",NaN,True,House,265000â‚¬ 265.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18046,2,https://www.realo.be/en/ellestraat-26-8470-gis...,"Ellestraat 26 3, 8470 Gistel",clean value,Gistel,"Ellestraat 26 3, 8470 Gistel",NaN,False,Flat,199000â‚¬ 199.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18047,2,https://www.realo.be/en/venneweg-11-2230-herse...,"Venneweg 11, 2230 Herselt, Herselt",clean value,"Herselt, Herselt","Venneweg 11, 2230 Herselt, Herselt",NaN,True,House,65000â‚¬ 65.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18048,2,https://www.realo.be/en/venneweg-9-2230-hersel...,"Venneweg 9, 2230 Herselt, Herselt",clean value,"Herselt, Herselt","Venneweg 9, 2230 Herselt, Herselt",NaN,True,House,55000â‚¬ 55.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18049,2,https://www.realo.be/en/leieweg-57-8510-marke/...,"Leieweg 57, 8510 Marke",clean value,Marke,"Leieweg 57, 8510 Marke",NaN,True,House,595000â‚¬ 595.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18050,2,https://www.realo.be/en/koningin-elisabethlei-...,"Koningin elisabethlei 1 8, 2300 Turnhout",clean value,Turnhout,"Koningin elisabethlei 1 8, 2300 Turnhout",NaN,False,Flat,229000â‚¬ 229.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18051,2,https://www.realo.be/en/rue-jean-damard-37-416...,"Rue jean damard 37, 4163 Tavier, Anthisnes",clean value,"Tavier, Anthisnes","Rue jean damard 37, 4163 Tavier, Anthisnes",NaN,True,House,385000â‚¬ 385.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18052,2,https://www.realo.be/en/stationsstraat-29-2200...,"Stationsstraat 29 214, 2200 Herentals",clean value,Herentals,"Stationsstraat 29 214, 2200 Herentals",NaN,False,Flat,170000â‚¬ 170.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18053,2,https://www.realo.be/en/gentse-steenweg-336-96...,"Gentse steenweg 336, 9620 Leeuwergem, Zottegem",clean value,"Leeuwergem, Zottegem","Gentse steenweg 336, 9620 Leeuwergem, Zottegem",NaN,True,House,339000â‚¬ 339.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18054,2,https://www.realo.be/en/nijverheidstraat-40-23...,"Nijverheidstraat 40, 2300 Turnhout",clean value,Turnhout,"Nijverheidstraat 40, 2300 Turnhout",NaN,True,House,210000â‚¬ 210.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18055,2,https://www.realo.be/en/hikstraat-48-2200-here...,"Hikstraat 48, 2200 Herentals",clean value,Herentals,"Hikstraat 48, 2200 Herentals",NaN,True,House,269000â‚¬ 269.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18056,2,https://www.realo.be/en/anjelierstraat-65-9000...,"Anjelierstraat 65, 9000 Ghent, Gent",clean value,"Ghent, Gent","Anjelierstraat 65, 9000 Ghent, Gent",NaN,False,Flat,204000â‚¬ 204.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18057,2,https://www.realo.be/en/oosterwijk-27-2260-ton...,"Oosterwijk 27, 2260 Tongerlo, Westerlo",clean value,"Tongerlo, Westerlo","Oosterwijk 27, 2260 Tongerlo, Westerlo",NaN,True,House,170000â‚¬ 170.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18058,2,https://www.realo.be/en/belikstraat-113-3550-z...,"Belikstraat 113, 3550 Zolder, Heusden-Zolder",clean value,Zolder,"Belikstraat 113, 3550 Zolder, Heusden-Zolder",NaN,True,House,279000â‚¬ 279.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18059,2,https://www.realo.be/en/vissersstraat-110-8380...,"Vissersstraat 110, 8380 Zeebrugge",clean value,Zeebrugge,"Vissersstraat 110, 8380 Zeebrugge",NaN,True,House,199000â‚¬ 199.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18060,2,https://www.realo.be/en/biddersstraat-27-8000-...,"Biddersstraat 27, 8000 Brugge",clean value,Brugge,"Biddersstraat 27, 8000 Brugge",NaN,True,House,220000â‚¬ 220.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18061,2,https://www.realo.be/en/molenstraat-2c-9880-aa...,"Molenstraat 2C, 9880 Aalter",clean value,Aalter,"Molenstraat 2C, 9880 Aalter",NaN,True,House,339000â‚¬ 339.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18062,2,https://www.realo.be/en/oostakker-40-2290-vors...,"Oostakker 40, 2290 Vorselaar",clean value,Vorselaar,"Oostakker 40, 2290 Vorselaar",NaN,True,House,230000â‚¬ 230.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18063,2,https://www.realo.be/en/pieter-de-bruynestraat...,"Pieter De Bruynestraat 35, 9300 Aalst",clean value,Aalst,"Pieter De Bruynestraat 35, 9300 Aalst",NaN,True,House,450000â‚¬ 450.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18064,2,https://www.realo.be/en/oostbroekstraat-4-8650...,"Oostbroekstraat 4, 8650 Merkem",clean value,Merkem,"Oostbroekstraat 4, 8650 Merkem",NaN,True,House,449000â‚¬ 449.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19026,2,https://www.realo.be/en/6030-marchienne-au-pon...,"Marchienne Etat, 6030 Marchienne-au-Pont, Char...",clean value,"Marchienne-au-Pont, Charleroi","Marchienne Etat, 6030 Marchienne-au-Pont, Char...",NaN,True,House,320000â‚¬ 320.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19027,2,https://www.realo.be/en/boulevard-auguste-reye...,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",clean value,Schaerbeek,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19039,2,https://www.realo.be/en/koning-albertstraat-21...,"Koning Albertstraat 21, 8210 Veldegem, Zedelgem",clean value,"Veldegem, Zedelgem","Koning Albertstraat 21, 8210 Veldegem, Zedelgem",NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19043,2,https://www.realo.be/en/stationsstraat-100-985...,"Stationsstraat 100, 9850 Landegem, Deinze",clean value,"Landegem, Deinze","Stationsstraat 100, 9850 Landegem, Deinze",NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19044,2,https://www.realo.be/en/lestpolder-63-9506-zan...,"Lestpolder 63, 9506 Zandbergen, Grimminge",clean value,"Zandbergen, Grimminge","Lestpolder 63, 9506 Zandbergen, Grimminge",NaN,True,House,199000â‚¬ 199.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19050,2,https://www.realo.be/en/ermietshoek-1-8480-ich...,"Ermietshoek 1 b, 8480 Ichtegem",clean value,Ichtegem,"Ermietshoek 1 b, 8480 Ichtegem",NaN,True,House,397000â‚¬ 397.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19051,2,https://www.realo.be/en/8300-knokke/5202369?l=...,"De Lac, 8300 Knokke",clean value,Knokke,"De Lac, 8300 Knokke",NaN,False,Flat,795000â‚¬ 795.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19052,2,https://www.realo.be/en/piers-de-raveschootlaa...,"Piers de raveschootlaan, 8300 Knokke",clean value,Knokke,"Piers de raveschootlaan, 8300 Knokke",NaN,False,Flat,447500â‚¬ 447.500,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19053,2,https://www.realo.be/en/8300-knokke/5202366?l=...,"Knokke Heilig Hart, 8300 Knokke",clean value,Knokke,"Knokke Heilig Hart, 8300 Knokke",NaN,False,Flat,430000â‚¬ 430.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19054,2,https://www.realo.be/en/8300-knokke/5202368?l=...,"Elisabethlaan - Het Zoute, 8300 Knokke, Knokke...",clean value,"Knokke, Knokke het zoute","Elisabethlaan - Het Zoute, 8300 Knokke, Knokke...",NaN,False,Flat,850000â‚¬ 850.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19055,2,https://www.realo.be/en/oude-vierschaarstraat-...,"Oude vierschaarstraat 3, 9831 Deurle",clean value,Deurle,"Oude vierschaarstraat 3, 9831 Deurle",NaN,True,House,875000â‚¬ 875.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19056,2,https://www.realo.be/en/omstraat-3720-kortesse...,"Omstraat, 3720 Kortessem",clean value,Kortessem,"Omstraat, 3720 Kortessem",NaN,False,Newbuild project,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19058,2,https://www.realo.be/en/2610-wilrijk/5196806?l...,"Sint-Augustinus, 2610 Wilrijk, Antwerpen",clean value,"Wilrijk, Antwerpen","Sint-Augustinus, 2610 Wilrijk, Antwerpen",NaN,True,House,1620000â‚¬ 1.620.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19062,2,https://www.realo.be/en/7500-tournai/5195305?l...,7500 Tournai,clean value,Tournai,7500 Tournai,NaN,True,House,185000â‚¬ 185.000,...,True,False,NaN,False,NaN,NaN,Yes,NaN,NaN,NaN
19063,2,https://www.realo.be/en/hille-125-8750-zweveze...,"Hille 125 0202, 8750 Zwevezele, Wingene",clean value,"Zwevezele, Wingene","Hille 125 0202, 8750 Zwevezele, Wingene",NaN,False,Flat,182000â‚¬ 182.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19064,2,https://www.realo.be/en/belgielaan-3-9051-sint...,"BelgiÃ«laan 3, 9051 Sint-Denijs-Westrem",clean value,Westrem,"BelgiÃ«laan 3, 9051 Sint-Denijs-Westrem",NaN,True,House,665000â‚¬ 665.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19065,2,https://www.realo.be/en/rue-du-chateau-41a-773...,"Rue du chateau 41A, 7730 Estaimpuis",clean value,Estaimpuis,"Rue du chateau 41A, 7730 Estaimpuis",NaN,True,House,317000â‚¬ 317.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19066,2,https://www.realo.be/en/rue-neuve-6-7640-antoi...,"Rue neuve 6, 7640 Antoing",clean value,Antoing,"Rue neuve 6, 7640 Antoing",NaN,True,House,59000â‚¬ 59.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19067,2,https://www.realo.be/en/1190-forest/5194011?l=...,1190 Forest,clean value,Forest,1190 Forest,NaN,False,Flat,485000â‚¬ 485.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19068,2,https://www.realo.be/en/van-gansenstraat-9-225...,"Van gansenstraat 9, 2250 Olen",clean value,Olen,"Van gansenstraat 9, 2250 Olen",NaN,True,House,192500â‚¬ 192.500,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19069,2,https://www.realo.be/en/rue-de-l'arsenal-7-1-7...,"Rue de l'arsenal 7/1, 7500 Tournai",clean value,Tournai,"Rue de l'arsenal 7/1, 7500 Tournai",NaN,False,Flat,60000â‚¬ 60.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19070,2,https://www.realo.be/en/1180-uccle/5194020?l=7...,1180 Uccle,clean value,Uccle,1180 Uccle,NaN,False,Flat,330000â‚¬ 330.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19071,2,https://www.realo.be/en/61775-1060-saint-gille...,1060 Saint-Gilles,clean value,Gilles,1060 Saint-Gilles,NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19072,2,https://www.realo.be/en/rue-de-marcasse-9-7340...,"Rue de marcasse 9, 7340 Wasmes, Colfontaine",clean value,"Wasmes, Colfontaine","Rue de marcasse 9, 7340 Wasmes, Colfontaine",NaN,True,House,162000â‚¬ 162.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19074,2,https://www.realo.be/en/6030-marchienne-au-pon...,"Marchienne Etat, 6030 Marchienne-au-Pont, Char...",clean value,"Marchienne-au-Pont, Charleroi","Marchienne Etat, 6030 Marchienne-au-Pont, Char...",NaN,True,House,320000â‚¬ 320.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19075,2,https://www.realo.be/en/boulevard-auguste-reye...,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",clean value,Schaerbeek,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19087,2,https://www.realo.be/en/koning-albertstraat-21...,"Koning Albertstraat 21, 8210 Veldegem, Zedelgem",clean value,"Veldegem, Zedelgem","Koning Albertstraat 21, 8210 Veldegem, Zedelgem",NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19091,2,https://www.realo.be/en/stationsstraat-100-985...,"Stationsstraat 100, 9850 Landegem, Deinze",clean value,"Landegem, Deinze","Stationsstraat 100, 9850 Landegem, Deinze",NaN,False,Flat,0,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19092,2,https://www.realo.be/en/lestpolder-63-9506-zan...,"Lestpolder 63, 9506 Zandbergen, Grimminge",clean value,"Zandbergen, Grimminge","Lestpolder 63, 9506 Zandbergen, Grimminge",NaN,True,House,199000â‚¬ 199.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19098,2,https://www.realo.be/en/ermietshoek-1-8480-ich...,"Ermietshoek 1 b, 8480 Ichtegem",clean value,Ichtegem,"Ermietshoek 1 b, 8480 Ichtegem",NaN,True,House,397000â‚¬ 397.000,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN

In [30]:
#Catch postcode where possible
import re
pattern = re.compile("\d{4}")
row_number = -1
for row in test_df["locality"]: 
    row_number+=1
    if type(row) is str: 
        search_result = pattern.search(row)
        if (search_result is not None) & (pd.isna(test_df['postcode'][row_number])): 
            search_match = pattern.search(row).group()
            test_df.loc[row_number, 'postcode'] = search_match

#I think I should work with subsets of the data instaed of a filter pattern
#However this would mess up with my row_number

test_df.head()

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,NaN,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,NaN,NaN,8730,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,NaN,NaN,1200,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,NaN,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW

In [31]:
import re
filter_pattern = re.compile("\d{4}")
row_number = -1
for row in test_df["locality"]: 
    row_number+=1
    if type(row) is str: 
        filter_criteria = filter_pattern.search(row)
        if filter_criteria is not None: 
            intermediate_value = test_df['loc_intermediate'][row_number]
            test_df.loc[row_number, 'loc_clean'] = intermediate_value

test_df.head(1000)

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,NaN,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,NaN,NaN,8730,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,NaN,NaN,1200,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,NaN,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW
5,6,8940340,NaN,NaN,4040,dirty_value,4040,True,HOUSE,189000,...,False,False,0,True,40,100,11,0,False,TO_BE_DONE_UP
6,6,8923626,NaN,NaN,4540,dirty_value,4540,True,MIXED_USE_BUILDING,465000,...,False,False,0,False,0,312,312,0,False,GOOD
7,6,8913667,NaN,NaN,1150,dirty_value,1150,True,APARTMENT_BLOCK,650000,...,False,True,4,True,150,301,301,0,False,GOOD
8,6,8693767,NaN,NaN,6870,dirty_value,6870,True,MIXED_USE_BUILDING,89000,...,False,False,0,False,0,96,96,0,False,TO_RENOVATE
9,6,8325945,NaN,NaN,4030,dirty_value,4030,True,MIXED_USE_BUILDING,129000,...,False,False,0,False,0,71,71,0,False,TO_BE_DONE_UP
10,6,8627972,NaN,NaN,9600,dirty_value,9600,True,APARTMENT_BLOCK,389000,...,False,True,22,False,0,205,205,0,False,GOOD
11,6,8783402,NaN,NaN,1030,dirty_value,1030,True,APARTMENT_BLOCK,399000,...,False,True,10,False,0,195,30,0,False,TO_RESTORE
12,6,8734225,NaN,NaN,4500,dirty_value,4500,True,APARTMENT_BLOCK,425000,...,False,True,0,True,366,603,114,0,False,AS_NEW
13,6,8730846,NaN,NaN,4500,dirty_value,4500,True,EXCEPTIONAL_PROPERTY,425000,...,False,True,0,True,366,603,114,0,False,AS_NEW
14,6,8560612,NaN,NaN,1200,dirty_value,1200,True,APARTMENT_BLOCK,1750000,...,False,True,20,True,60,270,270,0,False,AS_NEW
15,6,8412149,NaN,NaN,3270,dirty_value,3270,True,APARTMENT_BLOCK,198000,...,False,False,0,False,0,119,119,0,False,TO_RENOVATE
16,6,8894232,NaN,NaN,6760,dirty_value,6760,True,APARTMENT_BLOCK,349000,...,False,False,0,False,0,63,63,0,False,TO_BE_DONE_UP
17,6,8928748,NaN,NaN,9290,dirty_value,9290,True,MIXED_USE_BUILDING,445000,...,False,True,16,False,0,200,200,0,False,GOOD
18,6,8860947,NaN,NaN,8000,dirty_value,8000,True,MANSION,659000,...,True,True,20,False,0,125,125,0,False,JUST_RENOVATED
19,6,8941858,NaN,NaN,1140,dirty_value,1140,True,APARTMENT_BLOCK,695000,...,False,False,0,False,0,350,350,0,False,TO_BE_DONE_UP
20,6,8916756,NaN,NaN,8000,dirty_value,8000,True,MANSION,795000,...,False,True,38,False,0,110,110,0,False,JUST_RENOVATED
21,6,8939722,NaN,NaN,6940,dirty_value,6940,True,EXCEPTIONAL_PROPERTY,845000,...,False,False,0,True,6500,7000,7000,0,False,GOOD
22,6,8597517,NaN,NaN,4671,dirty_value,4671,True,APARTMENT_BLOCK,225000,...,False,True,150,False,0,315,315,0,False,TO_BE_DONE_UP
23,6,8913670,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,280000,...,False,False,0,True,55,120,49,0,False,TO_BE_DONE_UP
24,6,8309310,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,1395000,...,False,False,0,False,0,196,196,0,False,JUST_RENOVATED
25,6,8157990,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,2375000,...,False,True,0,False,0,183,183,0,False,JUST_RENOVATED
26,6,7701433,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,5000000,...,False,True,70,True,198,1988,1988,0,False,AS_NEW
27,6,7701432,NaN,NaN,1070,dirty_value,1070,True,MIXED_USE_BUILDING,5000000,...,False,True,70,True,198,1988,1988,0,False,AS_NEW
28,6,8866543,NaN,NaN,6030,dirty_value,6030,True,APARTMENT_BLOCK,275000,...,False,False,0,False,0,167,167,0,False,TO_BE_DONE_UP
29,6,8894789,NaN,NaN,1030,dirty_value,1030,True,APARTMENT_BLOCK,520000,...,False,True,15,True,65,147,147,0,False,TO_BE_DONE_UP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,6,7629200,NaN,NaN,6001,dirty_value,6001,True,MIXED_USE_BUILDING,160000,...,False,False,0,False,0,0,0,0,False,GOOD
971,6,8690694,NaN,NaN,9200,dirty_value,9200,True,APARTMENT_BLOCK,394200,...,False,False,0,False,0,0,0,0,False,NaN
972,6,8184732,NaN,NaN,2880,dirty_value,2880,True,APARTMENT_BLOCK,524000,...,False,True,0,False,0,0,361,0,False,AS_NEW
973,6,8879576,NaN,NaN,4040,dirty_value,4040,True,APARTMENT_BLOCK,100000,...,False,False,0,False,0,0,0,0,False,Not specified
974,6,8953507,NaN,NaN,1070,dirty_value,1070,True,APARTMENT_BLOCK,150000,...,False,False,0,False,0,0,0,0,False,Not specified
975,6,8857057,NaN,NaN,6110,dirty_value,6110,True,APARTMENT_BLOCK,295000,...,False,False,0,False,0,0,79,0,False,GOOD
976,6,8589848,NaN,NaN,9240,dirty_value,9240,True,APARTMENT_BLOCK,425000,...,False,True,0,False,0,1867,1867,0,False,TO_RESTORE
977,6,8589768,NaN,NaN,8760,dirty_value,8760,True,HOUSE,1500000,...,False,False,0,False,0,0,0,0,False,NaN
978,6,8939764,NaN,NaN,9620,dirty_value,9620,True,APARTMENT_BLOCK,2500000,...,False,False,0,False,0,0,0,0,False,Not specified
979,6,8649295,NaN,NaN,6500,dirty_value,6500,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,0,0,0,False,NaN
980,6,8727500,NaN,NaN,7700,dirty_value,7700,True,HOUSE,136615,...,False,False,0,False,0,0,0,0,False,Not specified
981,6,8732887,NaN,NaN,8770,dirty_value,8770,True,MIXED_USE_BUILDING,1000000,...,False,False,0,False,0,800,800,0,False,Not specified
982,6,8944032,NaN,NaN,6464,dirty_value,6464,True,MIXED_USE_BUILDING,350000,...,True,True,40,False,0,1800,1800,0,False,NaN
983,6,8936220,NaN,NaN,1000,dirty_value,1000,True,APARTMENT_BLOCK,850000,...,False,False,0,False,0,0,0,0,False,TO_BE_DONE_UP
984,6,8714772,NaN,NaN,5000,dirty_value,5000,True,APARTMENT_BLOCK,2050000,...,False,True,0,False,0,0,0,0,False,TO_RENOVATE
985,6,8797738,NaN,NaN,7134,dirty_value,7134,True,MIXED_USE_BUILDING,198000,...,False,True,0,False,0,0,0,0,False,NaN
986,6,8843305,NaN,NaN,9700,dirty_value,9700,True,APARTMENT_BLOCK,1395000,...,False,False,0,False,0,0,0,0,False,Not specified
987,6,8842796,NaN,NaN,9700,dirty_value,9700,True,MIXED_USE_BUILDING,1395000,...,False,False,0,False,0,0,0,0,False,Not specified
988,6,8904664,NaN,NaN,7021,dirty_value,7021,True,MIXED_USE_BUILDING,0,...,False,False,0,False,0,0,0,0,False,Not specified
989,6,8056306,NaN,NaN,7500,dirty_value,7500,True,MIXED_USE_BUILDING,1490000,...,False,False,0,False,0,832,832,0,False,TO_RENOVATE
990,6,8914568,NaN,NaN,7800,dirty_value,7800,True,MIXED_USE_BUILDING,185000,...,False,False,0,False,0,0,0,0,False,Not specified
991,6,8936218,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,850000,...,False,False,0,False,0,0,0,0,False,NaN
992,6,8878221,NaN,NaN,9050,dirty_value,9050,True,APARTMENT_BLOCK,1400000,...,False,False,0,False,0,0,0,0,False,Not specified
993,6,8802095,NaN,NaN,1730,dirty_value,1730,True,MIXED_USE_BUILDING,509000,...,False,False,0,False,0,375,375,0,False,GOOD
994,6,8601578,NaN,NaN,4101,dirty_value,4101,True,MIXED_USE_BUILDING,109000,...,False,True,25,True,94,219,219,0,False,TO_BE_DONE_UP
995,6,8930197,NaN,NaN,6856,dirty_value,6856,True,APARTMENT_BLOCK,230000,...,False,True,0,False,0,487,487,0,False,GOOD
996,6,8874978,NaN,NaN,5550,dirty_value,5550,True,APARTMENT_BLOCK,199000,...,False,True,0,False,0,513,513,0,False,GOOD
997,6,8884440,NaN,NaN,7864,dirty_value,7864,True,MIXED_USE_BUILDING,400000,...,False,False,0,False,0,829,829,0,False,GOOD
998,6,8811053,NaN,NaN,4350,dirty_value,4350,True,MIXED_USE_BUILDING,400000,...,False,True,0,True,36,2486,61,0,False,GOOD
999,6,8840809,NaN,NaN,3400,dirty_value,3400,True,MIXED_USE_BUILDING,249000,...,False,False,0,False,0,1116,51,0,False,TO_RENOVATE

In [32]:
test_df[test_df["loc_clean"]!= "clean value"].head(-1000)

,source,hyperlink,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,price,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,NaN,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,295000,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,NaN,NaN,8730,dirty_value,8730,True,VILLA,675000,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,250000,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,NaN,NaN,1200,dirty_value,1200,True,HOUSE,545000,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,NaN,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,500000,...,False,False,0,True,60,193,193,0,False,AS_NEW
5,6,8940340,NaN,NaN,4040,dirty_value,4040,True,HOUSE,189000,...,False,False,0,True,40,100,11,0,False,TO_BE_DONE_UP
6,6,8923626,NaN,NaN,4540,dirty_value,4540,True,MIXED_USE_BUILDING,465000,...,False,False,0,False,0,312,312,0,False,GOOD
7,6,8913667,NaN,NaN,1150,dirty_value,1150,True,APARTMENT_BLOCK,650000,...,False,True,4,True,150,301,301,0,False,GOOD
8,6,8693767,NaN,NaN,6870,dirty_value,6870,True,MIXED_USE_BUILDING,89000,...,False,False,0,False,0,96,96,0,False,TO_RENOVATE
9,6,8325945,NaN,NaN,4030,dirty_value,4030,True,MIXED_USE_BUILDING,129000,...,False,False,0,False,0,71,71,0,False,TO_BE_DONE_UP
10,6,8627972,NaN,NaN,9600,dirty_value,9600,True,APARTMENT_BLOCK,389000,...,False,True,22,False,0,205,205,0,False,GOOD
11,6,8783402,NaN,NaN,1030,dirty_value,1030,True,APARTMENT_BLOCK,399000,...,False,True,10,False,0,195,30,0,False,TO_RESTORE
12,6,8734225,NaN,NaN,4500,dirty_value,4500,True,APARTMENT_BLOCK,425000,...,False,True,0,True,366,603,114,0,False,AS_NEW
13,6,8730846,NaN,NaN,4500,dirty_value,4500,True,EXCEPTIONAL_PROPERTY,425000,...,False,True,0,True,366,603,114,0,False,AS_NEW
14,6,8560612,NaN,NaN,1200,dirty_value,1200,True,APARTMENT_BLOCK,1750000,...,False,True,20,True,60,270,270,0,False,AS_NEW
15,6,8412149,NaN,NaN,3270,dirty_value,3270,True,APARTMENT_BLOCK,198000,...,False,False,0,False,0,119,119,0,False,TO_RENOVATE
16,6,8894232,NaN,NaN,6760,dirty_value,6760,True,APARTMENT_BLOCK,349000,...,False,False,0,False,0,63,63,0,False,TO_BE_DONE_UP
17,6,8928748,NaN,NaN,9290,dirty_value,9290,True,MIXED_USE_BUILDING,445000,...,False,True,16,False,0,200,200,0,False,GOOD
18,6,8860947,NaN,NaN,8000,dirty_value,8000,True,MANSION,659000,...,True,True,20,False,0,125,125,0,False,JUST_RENOVATED
19,6,8941858,NaN,NaN,1140,dirty_value,1140,True,APARTMENT_BLOCK,695000,...,False,False,0,False,0,350,350,0,False,TO_BE_DONE_UP
20,6,8916756,NaN,NaN,8000,dirty_value,8000,True,MANSION,795000,...,False,True,38,False,0,110,110,0,False,JUST_RENOVATED
21,6,8939722,NaN,NaN,6940,dirty_value,6940,True,EXCEPTIONAL_PROPERTY,845000,...,False,False,0,True,6500,7000,7000,0,False,GOOD
22,6,8597517,NaN,NaN,4671,dirty_value,4671,True,APARTMENT_BLOCK,225000,...,False,True,150,False,0,315,315,0,False,TO_BE_DONE_UP
23,6,8913670,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,280000,...,False,False,0,True,55,120,49,0,False,TO_BE_DONE_UP
24,6,8309310,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,1395000,...,False,False,0,False,0,196,196,0,False,JUST_RENOVATED
25,6,8157990,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,2375000,...,False,True,0,False,0,183,183,0,False,JUST_RENOVATED
26,6,7701433,NaN,NaN,1000,dirty_value,1000,True,MIXED_USE_BUILDING,5000000,...,False,True,70,True,198,1988,1988,0,False,AS_NEW
27,6,7701432,NaN,NaN,1070,dirty_value,1070,True,MIXED_USE_BUILDING,5000000,...,False,True,70,True,198,1988,1988,0,False,AS_NEW
28,6,8866543,NaN,NaN,6030,dirty_value,6030,True,APARTMENT_BLOCK,275000,...,False,False,0,False,0,167,167,0,False,TO_BE_DONE_UP
29,6,8894789,NaN,NaN,1030,dirty_value,1030,True,APARTMENT_BLOCK,520000,...,False,True,15,True,65,147,147,0,False,TO_BE_DONE_UP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92038,3,NaN,NaN,NaN,1140,dirty_value,1140,False,NaN,215000â‚¬,...,True,NaN,NaN,False,NaN,NaN,NaN,2,0,Good
92039,3,NaN,NaN,NaN,2100,dirty_value,2100,False,NaN,255000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,As new
92040,3,NaN,NaN,NaN,8370,dirty_value,8370,False,NaN,129000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,To be done up
92041,3,NaN,NaN,NaN,1300,dirty_value,1300,False,NaN,320000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,3,0,Not specified
92042,3,NaN,NaN,NaN,1210,dirty_value,1210,False,NaN,299000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,3,0,As new
92043,3,NaN,NaN,NaN,8370,dirty_value,8370,False,NaN,495000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,3,0,As new
92044,3,NaN,NaN,NaN,2600,dirty_value,2600,False,NaN,195000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,1,0,Good
92045,3,NaN,NaN,NaN,9400,dirty_value,9400,False,NaN,210743â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,As new
92046,3,NaN,NaN,NaN,6000,dirty_value,6000,False,NaN,110000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,1,0,Good
92047,3,NaN,NaN,NaN,2170,dirty_value,2170,False,NaN,240000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,As new
92048,3,NaN,NaN,NaN,9000,dirty_value,9000,False,NaN,349000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Good
92049,3,NaN,NaN,NaN,4020,dirty_value,4020,False,NaN,110000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,To be done up
92050,3,NaN,NaN,NaN,8400,dirty_value,8400,False,NaN,127500â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Not specified
92051,3,NaN,NaN,NaN,1500,dirty_value,1500,False,NaN,210000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Good
92052,3,NaN,NaN,NaN,8400,dirty_value,8400,False,NaN,160000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Good
92053,3,NaN,NaN,NaN,8400,dirty_value,8400,False,NaN,160000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Not specified
92054,3,NaN,NaN,NaN,8400,dirty_value,8400,False,NaN,275000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,3,0,Good
92055,3,NaN,NaN,NaN,8400,dirty_value,8400,False,NaN,149000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,3,0,To be done up
92056,3,NaN,NaN,NaN,3630,dirty_value,3630,False,NaN,195000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,As new
92057,3,NaN,NaN,NaN,1080,dirty_value,1080,False,NaN,120000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,4,0,Good
92058,3,NaN,NaN,NaN,8740,dirty_value,8740,False,NaN,299500â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Good
92059,3,NaN,NaN,NaN,8370,dirty_value,8370,False,NaN,265000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Good
92060,3,NaN,NaN,NaN,8430,dirty_value,8430,False,NaN,315000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Not specified
92061,3,NaN,NaN,NaN,8000,dirty_value,8000,False,NaN,189000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Not specified
92062,3,NaN,NaN,NaN,8800,dirty_value,8800,False,NaN,130000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Not specified
92063,3,NaN,NaN,NaN,8430,dirty_value,8430,False,NaN,189000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,As new
92064,3,NaN,NaN,NaN,1030,dirty_value,1030,False,NaN,179000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,4,0,Good
92065,3,NaN,NaN,NaN,1140,dirty_value,1140,False,NaN,179000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,4,0,Good
92066,3,NaN,NaN,NaN,8020,dirty_value,8020,False,NaN,445000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,3,0,Good
92067,3,NaN,NaN,NaN,5020,dirty_value,5020,False,NaN,265000â‚¬,...,False,NaN,NaN,False,NaN,NaN,NaN,2,0,Good

In [33]:
#Catch value before the pc 
import re

if 'address' not in test_df.columns:
    index = test_df.columns.get_loc('locality')
    test_df.insert(index, "address", "")
    
filter_pattern = re.compile("(, ){0,1}\d{4}")
pattern = re.compile("^([a-zA-ZÃ€-Ã¿ -]+){1,}([0-9]+ ){0,}([a-zA-ZÃ€-Ã¿0-9]+){0,}")
row_number = -1
for row in test_df["locality"]: 
    row_number+=1
    if type(row) is str: 
        filter_criteria = filter_pattern.search(row)
        if filter_criteria is not None: 
            search_result = pattern.search(row)
            if search_result is not None: 
                search_match = pattern.search(row).group()
                test_df.loc[row_number, 'address'] = search_match
                
test_df.head()

,source,hyperlink,address,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
0,6,8901695,,NaN,NaN,4180,dirty_value,4180,True,MIXED_USE_BUILDING,...,False,True,36,True,1000,1403,1403,0,False,GOOD
1,6,8747010,,NaN,NaN,8730,dirty_value,8730,True,VILLA,...,False,False,0,True,977,1526,1526,0,False,AS_NEW
2,6,8775843,,NaN,NaN,4020,dirty_value,4020,True,APARTMENT_BLOCK,...,False,False,0,False,0,760,760,0,False,TO_RENOVATE
3,6,8910441,,NaN,NaN,1200,dirty_value,1200,True,HOUSE,...,False,False,0,False,0,63,63,0,False,JUST_RENOVATED
4,6,8758672,,NaN,NaN,1190,dirty_value,1190,True,MIXED_USE_BUILDING,...,False,False,0,True,60,193,193,0,False,AS_NEW

In [34]:
test_df[test_df["address"]!= ""].head(1000)

,source,hyperlink,address,locality,loc_clean,loc_intermediate,loc_dirty,postcode,house_is,property_subtype,...,open_fire,terrace,terrace_area,garden,garden_area,land_surface,land_plot_surface,facades_number,swimming_pool_has,building_state
18034,2,https://www.realo.be/en/rue-rimiere-105-4120-r...,Rue RimiÃ¨re 105,"Rue RimiÃ¨re 105, 4120 Rotheux-RimiÃ¨re, NeuprÃ©","Rotheux-RimiÃ¨re, NeuprÃ©","Rotheux-RimiÃ¨re, NeuprÃ©","Rue RimiÃ¨re 105, 4120 Rotheux-RimiÃ¨re, NeuprÃ©",4120,True,House,...,False,False,NaN,False,NaN,NaN,No,NaN,False,NaN
18035,2,https://www.realo.be/en/sint-truidensesteenweg...,Sint-Truidensesteenweg 95A,"Sint-Truidensesteenweg 95A A, 3350 Orsmaal-Gus...","Orsmaal-Gussenhoven, Linter","Orsmaal-Gussenhoven, Linter","Sint-Truidensesteenweg 95A A, 3350 Orsmaal-Gus...",3350,True,House,...,False,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18036,2,https://www.realo.be/en/augustijnenlaan-77-220...,Augustijnenlaan 77 201,"Augustijnenlaan 77 201, 2200 Herentals",Herentals,Herentals,"Augustijnenlaan 77 201, 2200 Herentals",2200,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18037,2,https://www.realo.be/en/averbodesesteenweg-19-...,Averbodesesteenweg 19,"Averbodesesteenweg 19, 2230 Herselt",Herselt,Herselt,"Averbodesesteenweg 19, 2230 Herselt",2230,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18038,2,https://www.realo.be/en/edward-pynaertkaai-21-...,Edward pynaertkaai 21,"Edward pynaertkaai 21, 9050 Ledeberg",Ledeberg,Ledeberg,"Edward pynaertkaai 21, 9050 Ledeberg",9050,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18040,2,https://www.realo.be/en/groenplein-33-9060-zel...,Groenplein 33 302,"Groenplein 33 302, 9060 Zelzate",Zelzate,Zelzate,"Groenplein 33 302, 9060 Zelzate",9060,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18041,2,https://www.realo.be/en/hoogveldstraat-21-3720...,Hoogveldstraat 21 D,"Hoogveldstraat 21 D, 3720 Kortessem",Kortessem,Kortessem,"Hoogveldstraat 21 D, 3720 Kortessem",3720,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18042,2,https://www.realo.be/en/eerste-meistraat-4-370...,Eerste-Meistraat 4,"Eerste-Meistraat 4, 3700 Tongeren",Tongeren,Tongeren,"Eerste-Meistraat 4, 3700 Tongeren",3700,False,Business,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18043,2,https://www.realo.be/en/roeselaarsestraat-84-8...,Roeselaarsestraat 84 8,"Roeselaarsestraat 84 8, 8870 Izegem",Izegem,Izegem,"Roeselaarsestraat 84 8, 8870 Izegem",8870,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18044,2,https://www.realo.be/en/meikeverstraat-12-2250...,Meikeverstraat 12,"Meikeverstraat 12, 2250 Olen",Olen,Olen,"Meikeverstraat 12, 2250 Olen",2250,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18045,2,https://www.realo.be/en/salvialaan-31-2260-oev...,Salvialaan 31,"Salvialaan 31, 2260 Oevel, Westerlo","Oevel, Westerlo","Oevel, Westerlo","Salvialaan 31, 2260 Oevel, Westerlo",2260,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18046,2,https://www.realo.be/en/ellestraat-26-8470-gis...,Ellestraat 26 3,"Ellestraat 26 3, 8470 Gistel",Gistel,Gistel,"Ellestraat 26 3, 8470 Gistel",8470,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18047,2,https://www.realo.be/en/venneweg-11-2230-herse...,Venneweg 11,"Venneweg 11, 2230 Herselt, Herselt","Herselt, Herselt","Herselt, Herselt","Venneweg 11, 2230 Herselt, Herselt",2230,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18048,2,https://www.realo.be/en/venneweg-9-2230-hersel...,Venneweg 9,"Venneweg 9, 2230 Herselt, Herselt","Herselt, Herselt","Herselt, Herselt","Venneweg 9, 2230 Herselt, Herselt",2230,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18049,2,https://www.realo.be/en/leieweg-57-8510-marke/...,Leieweg 57,"Leieweg 57, 8510 Marke",Marke,Marke,"Leieweg 57, 8510 Marke",8510,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18050,2,https://www.realo.be/en/koningin-elisabethlei-...,Koningin elisabethlei 1 8,"Koningin elisabethlei 1 8, 2300 Turnhout",Turnhout,Turnhout,"Koningin elisabethlei 1 8, 2300 Turnhout",2300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18051,2,https://www.realo.be/en/rue-jean-damard-37-416...,Rue jean damard 37,"Rue jean damard 37, 4163 Tavier, Anthisnes","Tavier, Anthisnes","Tavier, Anthisnes","Rue jean damard 37, 4163 Tavier, Anthisnes",4163,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18052,2,https://www.realo.be/en/stationsstraat-29-2200...,Stationsstraat 29 214,"Stationsstraat 29 214, 2200 Herentals",Herentals,Herentals,"Stationsstraat 29 214, 2200 Herentals",2200,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18053,2,https://www.realo.be/en/gentse-steenweg-336-96...,Gentse steenweg 336,"Gentse steenweg 336, 9620 Leeuwergem, Zottegem","Leeuwergem, Zottegem","Leeuwergem, Zottegem","Gentse steenweg 336, 9620 Leeuwergem, Zottegem",9620,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18054,2,https://www.realo.be/en/nijverheidstraat-40-23...,Nijverheidstraat 40,"Nijverheidstraat 40, 2300 Turnhout",Turnhout,Turnhout,"Nijverheidstraat 40, 2300 Turnhout",2300,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18055,2,https://www.realo.be/en/hikstraat-48-2200-here...,Hikstraat 48,"Hikstraat 48, 2200 Herentals",Herentals,Herentals,"Hikstraat 48, 2200 Herentals",2200,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18056,2,https://www.realo.be/en/anjelierstraat-65-9000...,Anjelierstraat 65,"Anjelierstraat 65, 9000 Ghent, Gent","Ghent, Gent","Ghent, Gent","Anjelierstraat 65, 9000 Ghent, Gent",9000,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18057,2,https://www.realo.be/en/oosterwijk-27-2260-ton...,Oosterwijk 27,"Oosterwijk 27, 2260 Tongerlo, Westerlo","Tongerlo, Westerlo","Tongerlo, Westerlo","Oosterwijk 27, 2260 Tongerlo, Westerlo",2260,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18058,2,https://www.realo.be/en/belikstraat-113-3550-z...,Belikstraat 113,"Belikstraat 113, 3550 Zolder, Heusden-Zolder",Zolder,Zolder,"Belikstraat 113, 3550 Zolder, Heusden-Zolder",3550,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18059,2,https://www.realo.be/en/vissersstraat-110-8380...,Vissersstraat 110,"Vissersstraat 110, 8380 Zeebrugge",Zeebrugge,Zeebrugge,"Vissersstraat 110, 8380 Zeebrugge",8380,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18060,2,https://www.realo.be/en/biddersstraat-27-8000-...,Biddersstraat 27,"Biddersstraat 27, 8000 Brugge",Brugge,Brugge,"Biddersstraat 27, 8000 Brugge",8000,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18061,2,https://www.realo.be/en/molenstraat-2c-9880-aa...,Molenstraat 2C,"Molenstraat 2C, 9880 Aalter",Aalter,Aalter,"Molenstraat 2C, 9880 Aalter",9880,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18062,2,https://www.realo.be/en/oostakker-40-2290-vors...,Oostakker 40,"Oostakker 40, 2290 Vorselaar",Vorselaar,Vorselaar,"Oostakker 40, 2290 Vorselaar",2290,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18063,2,https://www.realo.be/en/pieter-de-bruynestraat...,Pieter De Bruynestraat 35,"Pieter De Bruynestraat 35, 9300 Aalst",Aalst,Aalst,"Pieter De Bruynestraat 35, 9300 Aalst",9300,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
18064,2,https://www.realo.be/en/oostbroekstraat-4-8650...,Oostbroekstraat 4,"Oostbroekstraat 4, 8650 Merkem",Merkem,Merkem,"Oostbroekstraat 4, 8650 Merkem",8650,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19894,2,https://www.realo.be/en/boulevard-auguste-reye...,Boulevard Auguste Reyers 8,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",Schaerbeek,Schaerbeek,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",1030,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19906,2,https://www.realo.be/en/koning-albertstraat-21...,Koning Albertstraat 21,"Koning Albertstraat 21, 8210 Veldegem, Zedelgem","Veldegem, Zedelgem","Veldegem, Zedelgem","Koning Albertstraat 21, 8210 Veldegem, Zedelgem",8210,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19910,2,https://www.realo.be/en/stationsstraat-100-985...,Stationsstraat 100,"Stationsstraat 100, 9850 Landegem, Deinze","Landegem, Deinze","Landegem, Deinze","Stationsstraat 100, 9850 Landegem, Deinze",9850,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19911,2,https://www.realo.be/en/lestpolder-63-9506-zan...,Lestpolder 63,"Lestpolder 63, 9506 Zandbergen, Grimminge","Zandbergen, Grimminge","Zandbergen, Grimminge","Lestpolder 63, 9506 Zandbergen, Grimminge",9506,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19917,2,https://www.realo.be/en/ermietshoek-1-8480-ich...,Ermietshoek 1 b,"Ermietshoek 1 b, 8480 Ichtegem",Ichtegem,Ichtegem,"Ermietshoek 1 b, 8480 Ichtegem",8480,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19918,2,https://www.realo.be/en/8300-knokke/5202369?l=...,De Lac,"De Lac, 8300 Knokke",Knokke,Knokke,"De Lac, 8300 Knokke",8300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19919,2,https://www.realo.be/en/piers-de-raveschootlaa...,Piers de raveschootlaan,"Piers de raveschootlaan, 8300 Knokke",Knokke,Knokke,"Piers de raveschootlaan, 8300 Knokke",8300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19920,2,https://www.realo.be/en/8300-knokke/5202366?l=...,Knokke Heilig Hart,"Knokke Heilig Hart, 8300 Knokke",Knokke,Knokke,"Knokke Heilig Hart, 8300 Knokke",8300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19921,2,https://www.realo.be/en/8300-knokke/5202368?l=...,Elisabethlaan - Het Zoute,"Elisabethlaan - Het Zoute, 8300 Knokke, Knokke...","Knokke, Knokke het zoute","Knokke, Knokke het zoute","Elisabethlaan - Het Zoute, 8300 Knokke, Knokke...",8300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19922,2,https://www.realo.be/en/oude-vierschaarstraat-...,Oude vierschaarstraat 3,"Oude vierschaarstraat 3, 9831 Deurle",Deurle,Deurle,"Oude vierschaarstraat 3, 9831 Deurle",9831,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19923,2,https://www.realo.be/en/omstraat-3720-kortesse...,Omstraat,"Omstraat, 3720 Kortessem",Kortessem,Kortessem,"Omstraat, 3720 Kortessem",3720,False,Newbuild project,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19925,2,https://www.realo.be/en/2610-wilrijk/5196806?l...,Sint-Augustinus,"Sint-Augustinus, 2610 Wilrijk, Antwerpen","Wilrijk, Antwerpen","Wilrijk, Antwerpen","Sint-Augustinus, 2610 Wilrijk, Antwerpen",2610,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19926,2,https://www.realo.be/en/rue-de-bruxelles-43-71...,Rue de bruxelles 43,"Rue de bruxelles 43, 7130 Binche",Binche,Binche,"Rue de bruxelles 43, 7130 Binche",7130,True,House,...,False,False,NaN,False,NaN,NaN,No,NaN,NaN,NaN
19927,2,https://www.realo.be/en/rue-saint-gilles-37-40...,Rue saint gilles 37,"Rue saint gilles 37, 4000 LiÃ¨ge, LiÃˆge","LiÃ¨ge, LiÃˆge","LiÃ¨ge, LiÃˆge","Rue saint gilles 37, 4000 LiÃ¨ge, LiÃˆge",4000,True,House,...,False,False,NaN,False,NaN,NaN,No,NaN,NaN,NaN
19928,2,https://www.realo.be/en/pierre-gasseestraat-7-...,Pierre gasseestraat 7,"Pierre gasseestraat 7, 1080 Molenbeek-Saint-Jean",Jean,Jean,"Pierre gasseestraat 7, 1080 Molenbeek-Saint-Jean",1080,False,Flat,...,False,False,NaN,False,NaN,NaN,No,NaN,NaN,NaN
19930,2,https://www.realo.be/en/hille-125-8750-zweveze...,Hille 125 0202,"Hille 125 0202, 8750 Zwevezele, Wingene","Zwevezele, Wingene","Zwevezele, Wingene","Hille 125 0202, 8750 Zwevezele, Wingene",0202,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19931,2,https://www.realo.be/en/belgielaan-3-9051-sint...,BelgiÃ«laan 3,"BelgiÃ«laan 3, 9051 Sint-Denijs-Westrem",Westrem,Westrem,"BelgiÃ«laan 3, 9051 Sint-Denijs-Westrem",9051,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19932,2,https://www.realo.be/en/rue-du-chateau-41a-773...,Rue du chateau 41A,"Rue du chateau 41A, 7730 Estaimpuis",Estaimpuis,Estaimpuis,"Rue du chateau 41A, 7730 Estaimpuis",7730,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19933,2,https://www.realo.be/en/rue-neuve-6-7640-antoi...,Rue neuve 6,"Rue neuve 6, 7640 Antoing",Antoing,Antoing,"Rue neuve 6, 7640 Antoing",7640,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19935,2,https://www.realo.be/en/van-gansenstraat-9-225...,Van gansenstraat 9,"Van gansenstraat 9, 2250 Olen",Olen,Olen,"Van gansenstraat 9, 2250 Olen",2250,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19936,2,https://www.realo.be/en/rue-de-l'arsenal-7-1-7...,Rue de l,"Rue de l'arsenal 7/1, 7500 Tournai",Tournai,Tournai,"Rue de l'arsenal 7/1, 7500 Tournai",7500,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19939,2,https://www.realo.be/en/rue-de-marcasse-9-7340...,Rue de marcasse 9,"Rue de marcasse 9, 7340 Wasmes, Colfontaine","Wasmes, Colfontaine","Wasmes, Colfontaine","Rue de marcasse 9, 7340 Wasmes, Colfontaine",7340,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19941,2,https://www.realo.be/en/6030-marchienne-au-pon...,Marchienne Etat,"Marchienne Etat, 6030 Marchienne-au-Pont, Char...","Marchienne-au-Pont, Charleroi","Marchienne-au-Pont, Charleroi","Marchienne Etat, 6030 Marchienne-au-Pont, Char...",6030,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19942,2,https://www.realo.be/en/boulevard-auguste-reye...,Boulevard Auguste Reyers 8,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",Schaerbeek,Schaerbeek,"Boulevard Auguste Reyers 8, 1030 Schaerbeek",1030,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19954,2,https://www.realo.be/en/koning-albertstraat-21...,Koning Albertstraat 21,"Koning Albertstraat 21, 8210 Veldegem, Zedelgem","Veldegem, Zedelgem","Veldegem, Zedelgem","Koning Albertstraat 21, 8210 Veldegem, Zedelgem",8210,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19958,2,https://www.realo.be/en/stationsstraat-100-985...,Stationsstraat 100,"Stationsstraat 100, 9850 Landegem, Deinze","Landegem, Deinze","Landegem, Deinze","Stationsstraat 100, 9850 Landegem, Deinze",9850,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19959,2,https://www.realo.be/en/lestpolder-63-9506-zan...,Lestpolder 63,"Lestpolder 63, 9506 Zandbergen, Grimminge","Zandbergen, Grimminge","Zandbergen, Grimminge","Lestpolder 63, 9506 Zandbergen, Grimminge",9506,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19965,2,https://www.realo.be/en/ermietshoek-1-8480-ich...,Ermietshoek 1 b,"Ermietshoek 1 b, 8480 Ichtegem",Ichtegem,Ichtegem,"Ermietshoek 1 b, 8480 Ichtegem",8480,True,House,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19966,2,https://www.realo.be/en/8300-knokke/5202369?l=...,De Lac,"De Lac, 8300 Knokke",Knokke,Knokke,"De Lac, 8300 Knokke",8300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN
19967,2,https://www.realo.be/en/piers-de-raveschootlaa...,Piers de raveschootlaan,"Piers de raveschootlaan, 8300 Knokke",Knokke,Knokke,"Piers de raveschootlaan, 8300 Knokke",8300,False,Flat,...,True,False,NaN,True,NaN,NaN,Yes,NaN,NaN,NaN